// Generated by Droppp. You probably shouldn't modify this file, your computer might explode!
// Timestamp: 2025-03-22 17:12:25

#include <stddef.h>

#include "droppp.h"


#include "example.h"

#include "example2.h"



// Drop-generated meta definition for char (BUILTIN).
const struct droppp_meta_type_s char_meta = {
    .name = "char",
    
    .size = sizeof(char),
    .parent = NULL
};

// Drop-generated meta definition for uint8_t (BUILTIN).
const struct droppp_meta_type_s uint8_t_meta = {
    .name = "uint8_t",
    
    .size = sizeof(uint8_t),
    .parent = NULL
};

// Drop-generated meta definition for uint16_t (BUILTIN).
const struct droppp_meta_type_s uint16_t_meta = {
    .name = "uint16_t",
    
    .size = sizeof(uint16_t),
    .parent = NULL
};

// Drop-generated meta definition for uint32_t (BUILTIN).
const struct droppp_meta_type_s uint32_t_meta = {
    .name = "uint32_t",
    
    .size = sizeof(uint32_t),
    .parent = NULL
};

// Drop-generated meta definition for uint64_t (BUILTIN).
const struct droppp_meta_type_s uint64_t_meta = {
    .name = "uint64_t",
    
    .size = sizeof(uint64_t),
    .parent = NULL
};

// Drop-generated meta definition for float (BUILTIN).
const struct droppp_meta_type_s float_meta = {
    .name = "float",
    
    .size = sizeof(float),
    .parent = NULL
};

// Drop-generated meta definition for double (BUILTIN).
const struct droppp_meta_type_s double_meta = {
    .name = "double",
    
    .size = sizeof(double),
    .parent = NULL
};

// Drop-generated meta definition for short (BUILTIN).
const struct droppp_meta_type_s short_meta = {
    .name = "short",
    
    .size = sizeof(short),
    .parent = NULL
};

// Drop-generated meta definition for Example (CLASS).
const struct droppp_meta_type_s Example_meta = {
    .name = "Example",
    
    .fields = {
        
        {
            .name = "foo",
            .type = &uint32_t_meta,
            .offset = (void*)DROPPP_OFFSETOF(Example, foo),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
        {
            .name = "text",
            .type = &char_meta,
            .offset = (void*)DROPPP_OFFSETOF(Example, text),
            .initialized = true,
            .is_array = true,
            .array_count = 64
        },
        
    },
    
    .size = sizeof(Example),
    .parent = NULL
};

// Drop-generated meta definition for OtherExample (CLASS).
const struct droppp_meta_type_s OtherExample_meta = {
    .name = "OtherExample",
    
    .fields = {
        
        {
            .name = "thing2",
            .type = &float_meta,
            .offset = (void*)DROPPP_OFFSETOF(OtherExample, thing2),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
        {
            .name = "otherThing",
            .type = &Example_meta,
            .offset = (void*)DROPPP_OFFSETOF(OtherExample, otherThing),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
    },
    
    .size = sizeof(OtherExample),
    .parent = NULL
};

// Drop-generated meta definition for AActor (CLASS).
const struct droppp_meta_type_s AActor_meta = {
    .name = "AActor",
    
    .fields = {
        
        {
            .name = "x",
            .type = &float_meta,
            .offset = (void*)DROPPP_OFFSETOF(AActor, x),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
        {
            .name = "y",
            .type = &float_meta,
            .offset = (void*)DROPPP_OFFSETOF(AActor, y),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
    },
    
    .size = sizeof(AActor),
    .parent = NULL
};

// Drop-generated meta definition for AOtherGuy (CLASS).
const struct droppp_meta_type_s AOtherGuy_meta = {
    .name = "AOtherGuy",
    
    .fields = {
        
        {
            .name = "z",
            .type = &float_meta,
            .offset = (void*)DROPPP_OFFSETOF(AOtherGuy, z),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
    },
    
    .size = sizeof(AOtherGuy),
    .parent = &AActor_meta
};
