// Generated by Droppp. You probably shouldn't modify this file, your computer might explode!
// Timestamp: 2025-04-30 11:45:39

#include <stddef.h>

#include "droppp.h"


// Reflecting char

// Reflecting uint8_t

// Reflecting uint16_t

// Reflecting uint32_t

// Reflecting uint64_t

// Reflecting float

// Reflecting double

// Reflecting short

// Reflecting Example

// Reflecting OtherExample

// Reflecting AActor

// Reflecting AOtherGuy



#include "example.h"

#include "example2.h"


class BaseTypes {
    public:
    
    
    static const struct droppp_meta_type_s char_meta;
    
    
    
    static const struct droppp_meta_type_s uint8_t_meta;
    
    
    
    static const struct droppp_meta_type_s uint16_t_meta;
    
    
    
    static const struct droppp_meta_type_s uint32_t_meta;
    
    
    
    static const struct droppp_meta_type_s uint64_t_meta;
    
    
    
    static const struct droppp_meta_type_s float_meta;
    
    
    
    static const struct droppp_meta_type_s double_meta;
    
    
    
    static const struct droppp_meta_type_s short_meta;
    
    
    
    
    
    
    
    
    
    
};



// Drop-generated meta definition for char (BUILTIN).

// Base type!
const struct droppp_meta_type_s BaseTypes::char_meta =

    (struct droppp_meta_type_s) {
    .name = "char",
    
    .size = sizeof(char),
    .parent = NULL
};

// Drop-generated meta definition for uint8_t (BUILTIN).

// Base type!
const struct droppp_meta_type_s BaseTypes::uint8_t_meta =

    (struct droppp_meta_type_s) {
    .name = "uint8_t",
    
    .size = sizeof(uint8_t),
    .parent = NULL
};

// Drop-generated meta definition for uint16_t (BUILTIN).

// Base type!
const struct droppp_meta_type_s BaseTypes::uint16_t_meta =

    (struct droppp_meta_type_s) {
    .name = "uint16_t",
    
    .size = sizeof(uint16_t),
    .parent = NULL
};

// Drop-generated meta definition for uint32_t (BUILTIN).

// Base type!
const struct droppp_meta_type_s BaseTypes::uint32_t_meta =

    (struct droppp_meta_type_s) {
    .name = "uint32_t",
    
    .size = sizeof(uint32_t),
    .parent = NULL
};

// Drop-generated meta definition for uint64_t (BUILTIN).

// Base type!
const struct droppp_meta_type_s BaseTypes::uint64_t_meta =

    (struct droppp_meta_type_s) {
    .name = "uint64_t",
    
    .size = sizeof(uint64_t),
    .parent = NULL
};

// Drop-generated meta definition for float (BUILTIN).

// Base type!
const struct droppp_meta_type_s BaseTypes::float_meta =

    (struct droppp_meta_type_s) {
    .name = "float",
    
    .size = sizeof(float),
    .parent = NULL
};

// Drop-generated meta definition for double (BUILTIN).

// Base type!
const struct droppp_meta_type_s BaseTypes::double_meta =

    (struct droppp_meta_type_s) {
    .name = "double",
    
    .size = sizeof(double),
    .parent = NULL
};

// Drop-generated meta definition for short (BUILTIN).

// Base type!
const struct droppp_meta_type_s BaseTypes::short_meta =

    (struct droppp_meta_type_s) {
    .name = "short",
    
    .size = sizeof(short),
    .parent = NULL
};

// Drop-generated meta definition for Example (CLASS).

// Standalone type!
const struct droppp_meta_type_s Example::meta =

    (struct droppp_meta_type_s) {
    .name = "Example",
    
    .fields = {
        
        {
            .name = "foo",
            .type = &BaseTypes::uint32_t_meta,
            
            .offset = (void*)DROPPP_OFFSETOF(Example, foo),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
        {
            .name = "text",
            .type = &BaseTypes::char_meta,
            
            .offset = (void*)DROPPP_OFFSETOF(Example, text),
            .initialized = true,
            .is_array = true,
            .array_count = 64
        },
        
    },
    
    .size = sizeof(Example),
    .parent = NULL
};

// Drop-generated meta definition for OtherExample (CLASS).

// Standalone type!
const struct droppp_meta_type_s OtherExample::meta =

    (struct droppp_meta_type_s) {
    .name = "OtherExample",
    
    .fields = {
        
        {
            .name = "thing2",
            .type = &BaseTypes::float_meta,
            
            .offset = (void*)DROPPP_OFFSETOF(OtherExample, thing2),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
        {
            .name = "otherThing",
            .type = &Example::meta, 
            .offset = (void*)DROPPP_OFFSETOF(OtherExample, otherThing),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
    },
    
    .size = sizeof(OtherExample),
    .parent = NULL
};

// Drop-generated meta definition for AActor (CLASS).

// Standalone type!
const struct droppp_meta_type_s AActor::meta =

    (struct droppp_meta_type_s) {
    .name = "AActor",
    
    .fields = {
        
        {
            .name = "x",
            .type = &BaseTypes::float_meta,
            
            .offset = (void*)DROPPP_OFFSETOF(AActor, x),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
        {
            .name = "y",
            .type = &BaseTypes::float_meta,
            
            .offset = (void*)DROPPP_OFFSETOF(AActor, y),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
    },
    
    .size = sizeof(AActor),
    .parent = NULL
};

// Drop-generated meta definition for AOtherGuy (CLASS).

// Standalone type!
const struct droppp_meta_type_s AOtherGuy::meta =

    (struct droppp_meta_type_s) {
    .name = "AOtherGuy",
    
    .fields = {
        
        {
            .name = "z",
            .type = &BaseTypes::float_meta,
            
            .offset = (void*)DROPPP_OFFSETOF(AOtherGuy, z),
            .initialized = true,
            .is_array = false,
            .array_count = 0
        },
        
    },
    
    .size = sizeof(AOtherGuy),
    .parent = &AActor::meta
};
