// Generated by Droppp. You probably shouldn't modify this file, your computer might explode!
// Timestamp: {{ timestamp }}

#include <stddef.h>

#include "droppp.h"

{% for include in includes %}
#include "{{ include }}"
{% endfor %}

{% for type in types %}
{% include 'type.c' %}
{% endfor %}
